name: graphq_ir
channels:
  - defaults
  - conda-forge
dependencies:
  - conda
  - cudatoolkit=11.0.221
  - python=3.7.7
  - pip=20.0.2
  - pip:
    - antlr4-python3-runtime==4.9.2
    - argparse==1.4.0
    - graphq-trans==0.1.0
    - huggingface-hub==0.7.0
    - numpy==1.19.5
    - torch==1.8.1
    - tqdm==4.62.3
    - transformers==4.1.1
    - rdflib==5.0.0
    - pandas==1.3.5
